version: '3.8'

services:
  clickhouse:
    image: clickhouse/clickhouse-server:25.12-alpine
    container_name: clickhouse-server
    restart: unless-stopped
    volumes:
      - "/var/lib/clickhouse/data:/var/lib/clickhouse/"
      - "/var/log/clickhouse-server:/var/log/clickhouse-server/"
    ports:
      - "8123:8123"  # HTTP интерфейс
      - "9000:9000"  # ClickHouse native protocol
      - "9009:9009"  # ClickHouse native protocol with SSL
      - "9004:9004"  # Interserver HTTP
      - "9005:9005"  # Interserver HTTPS
    environment:
      - CLICKHOUSE_DB=${CLICKHOUSE_DB}
      - CLICKHOUSE_USER=${CLICKHOUSE_USER}
      - CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD}
      - CLICKHOUSE_MAX_MEMORY_USAGE=${CLICKHOUSE_MEMORY_LIMIT:-4G}
      - CLICKHOUSE_MAX_CONCURRENT_QUERIES=100
      - CLICKHOUSE_MAX_CONNECTIONS=4096
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
      - TZ=Europe/Moscow
      # Логирование
      - CLICKHOUSE_LOG_LEVEL=error
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8123/ping" ]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 40s
